# 1. update-alternatives --set editor /usr/bin/vim.basic
# 2. user setting:  (.selected_editor)
#     Generated by /usr/bin/select-editor
#     SELECTED_EDITOR=”/usr/bin/vim.basic”

# 3. export var EDITOR (I think this is the most useful)
export EDITOR="vim"
